namespace UI.ViewModels;

/// <summary>
/// AutoGenerated class, Unused for now.
/// </summary>
public partial class MainWindowViewModel : ViewModelBase
{
    public string Greeting { get; } = "Your moms car.";

}
